### ISSUE TITLE
No verification email code sent

### ISSUE THREAD

**Issue by enkidumeme** [bithumb-pro/bithumb.pro-official-api-docs#79]
I am trying to generate an API key, but I do not receive the email with the verification key. I clicked "send" several times and I tried different computers and browsers (Win10/Firefox, Macbook/Chrome). The emails are not in the spam folder, either.

**Comment by t0m1sacat** [comment]
Check mail trash,Or contact bithumb customer service to change an email

**Comment by chriscarlino** [comment]
@enkidumeme Did you get this issue resolved?  I am having the same problem

**Comment by bithumb-pro** [comment]
1. Have you checked the spam folder of your email? If you find that your email service provider is pushing BG emails into your spam folder, you can mark them as “safe” by whitelisting BG’s email addresses. You can refer to How to Whitelist BG Emails to set it up.
Addresses to whitelist:
donotreply@bitglobal.com
2. Is your email client or service provider working normally? You can check the email server settings to confirm that there isn’t any security conflict caused by your firewall or antivirus software.
3. Is your email inbox full? If you have reached the limit, you won't be able to send or receive emails. You can delete some of the old emails to free up some space for more emails.
4. If possible, register from common email domains, such as Gmail, Outlook, etc.
5. At last you can change your email by contact bithumb customer service.
