### ISSUE TITLE
Verification Email for API Key 

### ISSUE THREAD

**Issue by chriscarlino** [bithumb-pro/bithumb.pro-official-api-docs#94]
I have been trying to create an API key and am not receiving the verification email. I have contacted support several times and was directed here. It is the correct email and is not going to spam folder. Please help

**Comment by t0m1sacat** [comment]
Please add donotreply@bitglobal.com to your white list, If alse can't receive the code email. Please change your account to gmail,You can  contact support and tell the them that you can't receive the email so you want change your email to gmail.

**Comment by bithumb-pro** [comment]
1. Have you checked the spam folder of your email? If you find that your email service provider is pushing BG emails into your spam folder, you can mark them as “safe” by whitelisting BG’s email addresses. You can refer to How to Whitelist BG Emails to set it up.
Addresses to whitelist:
donotreply@bitglobal.com
2. Is your email client or service provider working normally? You can check the email server settings to confirm that there isn’t any security conflict caused by your firewall or antivirus software.
3. Is your email inbox full? If you have reached the limit, you won't be able to send or receive emails. You can delete some of the old emails to free up some space for more emails.
4. If possible, register from common email domains, such as Gmail, Outlook, etc.
5. At last you can change your email by contact bithumb customer service.
